CREATE USER tst IDENTIFIED BY tst DEFAULT TABLESPACE SBRFTBS TEMPORARY TABLESPACE TEMP PROFILE DEFAULT ACCOUNT UNLOCK ;
  -- 2 Roles for tst 
  GRANT CONNECT TO tst;
  GRANT RESOURCE TO tst;
  ALTER USER tst DEFAULT ROLE ALL;
  -- 7 System Privileges for tst 
  GRANT ALTER SESSION TO tst;
  GRANT CREATE DATABASE LINK TO tst;
  GRANT CREATE JOB TO tst;
  GRANT CREATE SESSION TO tst;
  GRANT CREATE TABLE TO tst;
  GRANT CREATE VIEW TO tst;
  GRANT UNLIMITED TABLESPACE TO tst;
  -- 1 Tablespace Quota for tst 
  ALTER USER tst QUOTA UNLIMITED ON SBRFTBS;
  -- 5 Object Privileges for tst 
    GRANT SELECT ON SYS.DBA_2PC_PENDING TO tst;
    GRANT SELECT ON SYS.DBA_PENDING_TRANSACTIONS TO tst;
    GRANT EXECUTE ON SYS.DBMS_LOCK TO tst;
    GRANT EXECUTE ON SYS.DBMS_SYSTEM TO tst;
    GRANT SELECT ON SYS.PENDING_TRANS$ TO tst;
